database_settings:
  app_data_base: app.db
  task_log_base: C:/scripts/alsey/netpeak_core/nc_analytics_team/telegram_bot/bot_db.db
access_managemet:
  tab_cmd:
    - admin
    - user
  tab_access:
    - admin